name: circular_progress_stack
description: This package use for easy to create multple circular progress bar. and you can set gradient and animated
version: 0.0.3
repository:  https://github.com/Trushar88/stackcircularprogressbar
homepage: https://github.com/Trushar88/stackcircularprogressbar/blob/main/example/lib/main.dart

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: